= Usage

== Example

After the installation you can call the command `+osivalidator+` in your
terminal which has the following usage:

[source,bash]
----
usage: osivalidator [-h] --data DATA [--rules RULES] [--type {SensorView,GroundTruth,SensorData}] [--output OUTPUT] [--timesteps TIMESTEPS] [--debug] [--verbose] [--parallel] [--format {None}]
                    [--blast BLAST] [--buffer BUFFER]

Validate data defined at the input

mandatory arguments:
--data DATA           Path to the file with OSI-serialized data.

optional arguments:
-h, --help            show this help message and exit
--rules RULES, -r RULES
                      Directory with text files containig rules.
--type {SensorView,GroundTruth,SensorData}, -t {SensorView,GroundTruth,SensorData}
                      Name of the type used to serialize data.
--output OUTPUT, -o OUTPUT
                      Output folder of the log files.
--timesteps TIMESTEPS
                      Number of timesteps to analyze. If -1, all.
--debug               Set the debug mode to ON.
--verbose, -v         Set the verbose mode to ON.
--parallel, -p        (Ignored) Set parallel mode to ON.
--format {None}, -f {None}
                      (Ignored) Set the format type of the trace.
--blast BLAST, -bl BLAST
                      Set the maximum in-memory storage count of OSI messages during validation.
--buffer BUFFER, -bu BUFFER
                      (Ignored) Set the buffer size to retrieve OSI messages from trace file. Set it to 0 if you do not want to use buffering at all.
----

To run the validation first you need an OSI trace file which consists of
multiple OSI messages. In the directory `+data+` of the repository we
already provide an example trace file which is called
`+20240221T141700Z_sv_300_2112_10_one_moving_object.osi+`.

To validate the trace file you simply call `+osivalidator+` and provide
the path to the trace:

[source,bash]
----
osivalidator --data data/20240221T141700Z_sv_300_2112_10_one_moving_object.osi
----

To validate trace files with rules defined in the comments of
`+*.proto+` files in the open-simulation-interface repository first you
need to generate them and then specify them:

[source,bash]
----
python rules2yml.py # Generates the rule directory
osivalidator --data data/20240221T141700Z_sv_300_2112_10_one_moving_object.osi --rules rules -p
----

The rules2yml.py generates a yml file for each OSI proto file containing the rules specified in OSI.
The yml files are located in the specified rules folder given as an input parameter.
Additionally, the script generates respective yml schema files to validate the rule yml files in <rules_folder>/schema.
The schema files contain the message names of the original OSI proto file and a list of applicable rules.
If a rule has an associated value, e.g. a string or a number, the type of the value is also checked.
When executing osivalidator, all rule files are validated against their respective schema.

If needed, the rules folder can be copied and modified for specific use cases, e.g. by adding or removing certain rules.
This way, osivalidation can be used with different sets of rules.

After successfully running the validation the following output is
generated:

[source,bash]
----
Instantiate logger ...
Reading data ...
Retrieving messages in osi trace file until 1290 ...
10 messages has been discovered in 8.273124694824219e-05 s
Collect validation rules ...

Caching ...
Caching done!
Warnings (8)
Ranges of timestamps    Message
----------------------  -----------------------------------------------------------------------------------------------------------------------------------------------------
[0, 9]                  SensorView.version.is_set(None) does not comply in SensorView
[0, 9]                  SensorView.sensor_id.is_set(None) does not comply in SensorView
[0, 9]                  SensorView.mounting_position.is_set(None) does not comply in SensorView
[0, 9]                  SensorView.host_vehicle_id.is_set(None) does not comply in SensorView
[0, 9]                  MovingObject.vehicle_attributes.check_if.is_set(None) does not comply in SensorView.global_ground_truth.moving_object
[0, 9]                  MovingObject.vehicle_attributes.check_if([{'is_equal_to': 2, 'target': 'this.type'}]) does not comply in SensorView.global_ground_truth.moving_object
[0, 9]                  Reference unresolved: GroundTruth to MovingObject (ID: 113)
[1, 9]                  MovingObject.pedestrian_attributes.check_if.is_equal_to(3) does not comply in SensorView.global_ground_truth.moving_object.type
----

The Output is a report of how many errors (here 0) and warnings (here
8) were found in the osi-message according to the defined rules in your
specified rules directory. The rules can be found under the tag
`+\rules+` in the *.proto files from the
https://github.com/OpenSimulationInterface/open-simulation-interface[osi
github].

For each error and warning there is a description on which timestamp it was found, the path to the rule and the path to the
osi-message is provided. The general format is:

[source,bash]
----
Errors (NUMBER_ERRORS) 
Ranges of timestamps                Message
--------------------------------    --------------------------------------------------------
[START_TIMESTAMP, END_TIMESTAMP]    PATH_TO_RULE(VALUE) does not comply in PATH_TO_OSI_FIELD

Warnings (NUMBER_WARNINGS) 
Ranges of timestamps    Message
--------------------------------    --------------------------------------------------------
[START_TIMESTAMP, END_TIMESTAMP]    PATH_TO_RULE(VALUE) does not comply in PATH_TO_OSI_FIELD
----

== Understanding Validation Output

To better understand the validation output let us use the example
above and describe the meaning of the lines. First of all one should
know that the rules to the fields are checked in a
https://en.wikipedia.org/wiki/Depth-first_search[depth-first-search]
(DFS) traversal manner. The validation starts with the top-level message `+SensorView+`, `+SensorData+` or `+GroundTruth+`
and goes in depth if the message is set. For example the message
below is checked but does not go further in depth because it is not
set (indicated by `+is_set(None)+`):

[source,bash]
----
[0, 9]                  SensorView.version.is_set(None) does not comply in SensorView
----

Some rules have conditions.
The vehicle_attributes of a moving object for example only have to be set, when the moving object is of type vehicle.
The following warning indicates, that it is checked that the moving object is of type vehicle (enum value 2) but the vehicle_attributes are not set.

[source,bash]
----
[0, 9]                  MovingObject.vehicle_attributes.check_if.is_set(None) does not comply in SensorView.global_ground_truth.moving_object
[0, 9]                  MovingObject.vehicle_attributes.check_if([{'is_equal_to': 2, 'target': 'this.type'}]) does not comply in SensorView.global_ground_truth.moving_object
----

== Custom Rules

Currently, the following rules exist:

[source,python]
----
is_greater_than: 1
is_greater_than_or_equal_to: 1
is_less_than_or_equal_to: 10
is_less_than: 2
is_equal: 1
is_different: 2
is_globally_unique:
refers_to: MovingObject
is_iso_country_code:
first_element: {is_equal: 0.13, is_greater_than: 0.13}
last_element: {is_equal: 0.13, is_greater_than: 0.13}
check_if: [{is_equal: 2, is_greater_than: 3, target: this.y}, {do_check: {is_equal: 1, is_less_than: 3}}]
is_set:
----

These rules can be added manually to the rules *.yml files like in the
example of the environmental conditions below (see
`+how-to-write-rules+` for more):

[source,yaml]
----
EnvironmentalConditions:
    ambient_illumination:
    time_of_day:
    unix_timestamp:
    atmospheric_pressure:
        - is_greater_than_or_equal_to: 80000
        - is_less_than_or_equal_to: 120000
    temperature:
        - is_greater_than_or_equal_to: 170
        - is_less_than_or_equal_to: 340
    relative_humidity:
        - is_greater_than_or_equal_to: 0
        - is_less_than_or_equal_to: 100
    precipitation:
    fog:
    TimeOfDay:
        seconds_since_midnight:
        - is_greater_than_or_equal_to: 0
        - is_less_than: 86400
----

Further custom rules can be implemented into the osi-validator (see
https://github.com/OpenSimulationInterface/osi-validation/blob/master/osivalidator/osi_rules_implementations.py[rules
implementation] for more).
