# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osi3/osi_sensorspecific.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='osi3/osi_sensorspecific.proto',
  package='osi3',
  syntax='proto2',
  serialized_options=_b('H\001'),
  serialized_pb=_b('\n\x1dosi3/osi_sensorspecific.proto\x12\x04osi3\"&\n\x17RadarSpecificObjectData\x12\x0b\n\x03rcs\x18\x01 \x01(\x01\"\x19\n\x17LidarSpecificObjectData\"\x1a\n\x18\x43\x61meraSpecificObjectData\"\x1e\n\x1cUltrasonicSpecificObjectDataB\x02H\x01')
)




_RADARSPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='RadarSpecificObjectData',
  full_name='osi3.RadarSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rcs', full_name='osi3.RadarSpecificObjectData.rcs', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=77,
)


_LIDARSPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='LidarSpecificObjectData',
  full_name='osi3.LidarSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=104,
)


_CAMERASPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='CameraSpecificObjectData',
  full_name='osi3.CameraSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=132,
)


_ULTRASONICSPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='UltrasonicSpecificObjectData',
  full_name='osi3.UltrasonicSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['RadarSpecificObjectData'] = _RADARSPECIFICOBJECTDATA
DESCRIPTOR.message_types_by_name['LidarSpecificObjectData'] = _LIDARSPECIFICOBJECTDATA
DESCRIPTOR.message_types_by_name['CameraSpecificObjectData'] = _CAMERASPECIFICOBJECTDATA
DESCRIPTOR.message_types_by_name['UltrasonicSpecificObjectData'] = _ULTRASONICSPECIFICOBJECTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadarSpecificObjectData = _reflection.GeneratedProtocolMessageType('RadarSpecificObjectData', (_message.Message,), dict(
  DESCRIPTOR = _RADARSPECIFICOBJECTDATA,
  __module__ = 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.RadarSpecificObjectData)
  ))
_sym_db.RegisterMessage(RadarSpecificObjectData)

LidarSpecificObjectData = _reflection.GeneratedProtocolMessageType('LidarSpecificObjectData', (_message.Message,), dict(
  DESCRIPTOR = _LIDARSPECIFICOBJECTDATA,
  __module__ = 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.LidarSpecificObjectData)
  ))
_sym_db.RegisterMessage(LidarSpecificObjectData)

CameraSpecificObjectData = _reflection.GeneratedProtocolMessageType('CameraSpecificObjectData', (_message.Message,), dict(
  DESCRIPTOR = _CAMERASPECIFICOBJECTDATA,
  __module__ = 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.CameraSpecificObjectData)
  ))
_sym_db.RegisterMessage(CameraSpecificObjectData)

UltrasonicSpecificObjectData = _reflection.GeneratedProtocolMessageType('UltrasonicSpecificObjectData', (_message.Message,), dict(
  DESCRIPTOR = _ULTRASONICSPECIFICOBJECTDATA,
  __module__ = 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.UltrasonicSpecificObjectData)
  ))
_sym_db.RegisterMessage(UltrasonicSpecificObjectData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
